### ISSUE TITLE
mfenced has background color

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax-demos-web#12]
mfenced displays with a colored background for some reason (debugging code that wasn't removed?)

Two examples:
```
<math display='block' xmlns='http://www.w3.org/1998/Math/MathML'>
<mfenced> <mrow><mn>2</mn><mi>x</mi><mo>+</mo><mi>y</mi> </mrow></mfenced>
</math>

<math display='block' xmlns='http://www.w3.org/1998/Math/MathML'>
<mfenced open=')' close='('> <mn>1</mn><mn>456</mn> <mrow><mn>2</mn><mi>x</mi><mo>+</mo><mi>y</mi> </mrow></mfenced>
</math>
```

Here's how they display:
![image](https://user-images.githubusercontent.com/1545836/41798875-3638c04c-7624-11e8-8872-3ca1ef7aaa47.png)

**Comment by dpvc** [comment]
Yes, this was some debugging code that was left in by accident in one of the betas.  It has since been removed.  Sorry about that!
