### ISSUE TITLE
error when using the demo tex2svg page

### ISSUE THREAD

**Issue by dtra** [mathjax/MathJax-demos-web#27]
Hi
I'm trying to run the demo at https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html
Didn't change anything, and when I hit render tex button, I get "Invalid option "family" (no default value)."
Firefox 68, Chrome 84, Windows 10, noticed this since Friday 28/08/2020.

**Comment by dpvc** [comment]
This is issue mathjax/MathJax#2512, and will be fixed in the next release (which I expect will be shortly, since there are several small issues like this that cropped up in v3.1).

**Comment by dpvc** [comment]
This has been fixed in v3.1.2
