### ISSUE TITLE
[Converter] minScaleAdjust should be scaled down just like scale

### ISSUE THREAD

**Issue by tomasr8** [mathjax/MathJax-demos-web#42]
This v2 config:

```js
MathJax.Hub.Config({
    "HTML-CSS": {
        scale: 100,
        minScaleAdjust: 50,
    },
});
```

gets converted into:
```js
window.MathJax = {
  chtml: {
    scale: 1,
    minScale: 50
  }
};
```

IIUC, `minScale` should also be scaled by a factor of 100 but currently it's just transferred .e.g. `Translate.transfer('chtml.minScale')` w/o any transformation.

**Comment by dpvc** [comment]
Thanks for catching that.  I've commit a fix, so it should be working now.

**Comment by tomasr8** [comment]
Thanks!
